server:
  compression:
    enabled: true
  tomcat:
    uri-encoding: utf-8
  port: 8200
spring:
  application:
    name: myapplication

zuul:
  ribbon:
    read-timeout: 6000
    socket-timeout: 6000
  strip-prefix: false
  add-proxy-headers: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 10000
  sensitive-headers: '*'
  routes:
    third:
      path: /third/**
    gateway:
      path: /gateway/**
    test:
      path: /exchange_tjdgm/**
      serviceId: exchange_tjdgm

ribbon:
  eager-load:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


#  适用于@EnableZuulProxy方式
#zuul:
#  prefix: /atguigu
#  ignored-services: "*"
#  routes:
#    mydept.serviceId: microservicecloud-dept
#    mydept.path: /mydept/**